replicaCount: 1

geth:
  jwtSecretName: jwt-secret
  jwtSecretFilename: jwt.hex
  httpRpcPort: 8545
  wsRpcPort: 8546
  authRpcPort: 8551
  p2pPort: 30303

image:
  repository: ethereum/client-go
  pullPolicy: IfNotPresent
  tag: ""

externalResources:
  resourceGroupName: ""
  loadBalancerIP: 0.0.0.0

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

resources: {}
  # limits:
  #   cpu: 4000m
  #   memory: 16Gi
  # requests:
  #   cpu: 2000m
  #   memory: 4Gi