apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geth.fullname" . }}-disk
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 2Ti